blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ ç¤¾åŒºè®¨è®º
    url: https://github.com/vultur/SmartEdu-Textbook/discussions
    about: åœ¨è¿™é‡Œè·å–å¸®åŠ©ã€è®¨è®ºéœ€æ±‚æˆ–äº¤æµå¿ƒå¾—
  - name: ğŸ™‹ æäº¤åé¦ˆ
    url: https://github.com/vultur/SmartEdu-Tools-App
    about: å…³äº SmartEdu Tools çš„é—®é¢˜æˆ–å»ºè®®
